language: r
cache: packages

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes

notifications:
  email:
    on_success: change
    on_failure: change

services:
    - xvfb
    
before_install:
    - export DISPLAY=:99.0
    - export RGL_USE_NULL=FALSE
    - tlmgr install index

apt_packages:
    - libssl-dev 
    - libftgl2 
    - libglu1-mesa-dev 
    - libftgl2 
    - libfreetype6-dev  
    - libxml2-dev
    
r_packages:
 - covr
 
after_success:
  - Rscript -e 'library(covr); codecov()'